const { expression } = require('mathjs')

exports.menuId = require('./menu')
exports.button = require('./button')
exports.tiktok = require('./tiktok')
exports.client = require('./client')
exports.yt = require('./youtube')
exports.matematika = require('./matematika')
exports.point = require('./point')
exports.st = require('./sticker')
exports.respons = require('./respons')
exports.sewa = require('./sewa')
exports.ttk = require('./tekateki')